#!/usr/bin/env bash
# harden-ubuntu-vault-host.sh — Ubuntu 24.04 hardening for the dedicated Opale Vault backend VM.
# Idempotent: can be run multiple times safely.

set -euo pipefail

SSH_PORT=2222
APP_PORT=8443
ALLOWED_SSH_CIDR=""
ALLOWED_APP_CIDR=""
ADMIN_USER="ubuntu"
APP_DIR="/opt/opale-vault"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssh-port) SSH_PORT="$2"; shift 2 ;;
    --app-port) APP_PORT="$2"; shift 2 ;;
    --allowed-ssh-cidr) ALLOWED_SSH_CIDR="$2"; shift 2 ;;
    --allowed-app-cidr) ALLOWED_APP_CIDR="$2"; shift 2 ;;
    --admin-user) ADMIN_USER="$2"; shift 2 ;;
    --app-dir) APP_DIR="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info() { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_section() { echo -e "\n${BLUE}━━━ $* ━━━${NC}"; }

run() {
  if [[ "$DRY_RUN" == true ]]; then
    echo -e "${YELLOW}[DRY-RUN]${NC} $*"
  else
    eval "$@"
  fi
}

write_file() {
  local path="$1"
  local content="$2"
  if [[ "$DRY_RUN" == true ]]; then
    echo -e "${YELLOW}[DRY-RUN]${NC} write $path"
    return
  fi
  if [[ -f "$path" && ! -f "${path}.bak" ]]; then
    cp "$path" "${path}.bak"
  fi
  cat > "$path" <<< "$content"
}

if [[ "$DRY_RUN" == false && "$EUID" -ne 0 ]]; then
  echo "Run as root: sudo bash harden-ubuntu-vault-host.sh"
  exit 1
fi

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

log_info "Dedicated Opale Vault backend hardening"
log_info "ssh_port=$SSH_PORT app_port=$APP_PORT admin_user=$ADMIN_USER app_dir=$APP_DIR"

log_section "1/11 — System updates"
run "apt-get update -qq"
run "DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq"
run "DEBIAN_FRONTEND=noninteractive apt-get autoremove -y -qq"
run "apt-get clean"
log_ok "System packages updated"

log_section "2/11 — Base packages"
run "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ca-certificates curl gnupg ufw fail2ban auditd audispd-plugins unattended-upgrades openssh-server"
log_ok "Base packages installed"

log_section "3/11 — Disable swap on the backend host"
if [[ "$DRY_RUN" == false ]]; then
  swapoff -a || true
  if [[ -f /etc/fstab ]]; then
    cp /etc/fstab /etc/fstab.bak-opale 2>/dev/null || true
    sed -i '/\sswap\s/s/^/# disabled-by-opale /' /etc/fstab
  fi
fi
log_ok "Swap disabled for the dedicated backend host"

log_section "4/11 — SSH hardening"
SSH_CONF="/etc/ssh/sshd_config.d/99-opale-vault.conf"
SSH_CONTENT="# Generated by harden-ubuntu-vault-host.sh
Port ${SSH_PORT}
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
MaxAuthTries 3
MaxSessions 4
LoginGraceTime 20
ClientAliveInterval 300
ClientAliveCountMax 2
DebianBanner no
LogLevel VERBOSE
AllowUsers ${ADMIN_USER}
Banner /etc/issue.net
"
write_file "$SSH_CONF" "$SSH_CONTENT"
write_file "/etc/issue.net" "UNAUTHORIZED ACCESS PROHIBITED. Connections are logged and audited."

if [[ "$DRY_RUN" == false ]]; then
  if sshd -t; then
    systemctl enable ssh --quiet
    systemctl restart ssh
    log_ok "SSH reloaded"
  else
    log_warn "Invalid SSH configuration; reverting"
    cp "${SSH_CONF}.bak" "$SSH_CONF" 2>/dev/null || rm -f "$SSH_CONF"
    exit 1
  fi
fi

log_section "5/11 — Firewall"
if [[ "$DRY_RUN" == false ]]; then
  ufw --force reset >/dev/null 2>&1 || true
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  if [[ -n "$ALLOWED_SSH_CIDR" ]]; then
    ufw allow from "$ALLOWED_SSH_CIDR" to any port "$SSH_PORT" proto tcp >/dev/null
  else
    ufw limit "$SSH_PORT"/tcp >/dev/null
  fi
  if [[ -n "$ALLOWED_APP_CIDR" ]]; then
    ufw allow from "$ALLOWED_APP_CIDR" to any port "$APP_PORT" proto tcp >/dev/null
  else
    ufw allow "$APP_PORT"/tcp >/dev/null
  fi
  ufw --force enable >/dev/null
fi
log_ok "Firewall configured"

log_section "6/11 — Fail2ban"
FAIL2BAN_CONF="/etc/fail2ban/jail.d/opale-vault.conf"
FAIL2BAN_CONTENT="[DEFAULT]
bantime = 2h
findtime = 10m
maxretry = 3
banaction = iptables-multiport

[sshd]
enabled = true
port = ${SSH_PORT}
logpath = %(sshd_log)s
backend = %(sshd_backend)s
"
write_file "$FAIL2BAN_CONF" "$FAIL2BAN_CONTENT"
run "systemctl enable fail2ban --quiet"
run "systemctl restart fail2ban"
log_ok "Fail2ban configured"

log_section "7/11 — Kernel sysctl"
SYSCTL_CONF="/etc/sysctl.d/99-opale-vault.conf"
SYSCTL_CONTENT="# Generated by harden-ubuntu-vault-host.sh
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 2
kernel.randomize_va_space = 2
fs.suid_dumpable = 0
"
write_file "$SYSCTL_CONF" "$SYSCTL_CONTENT"
run "sysctl -p $SYSCTL_CONF >/dev/null 2>&1 || true"
log_ok "Kernel hardening applied"

log_section "8/11 — Audit rules"
AUDIT_RULES="/etc/audit/rules.d/opale-vault.rules"
AUDIT_CONTENT="# Generated by harden-ubuntu-vault-host.sh
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /etc/ssh/sshd_config.d/ -p wa -k sshd_config
-w /etc/docker/daemon.json -p wa -k docker_config
-w ${APP_DIR}/deploy.env -p wa -k opale_deploy_env
-w ${APP_DIR}/.env -p wa -k opale_runtime_env
"
write_file "$AUDIT_RULES" "$AUDIT_CONTENT"
run "systemctl enable auditd --quiet"
run "systemctl restart auditd"
log_ok "Auditd configured"

log_section "9/11 — Docker Engine"
if ! command -v docker >/dev/null 2>&1; then
  run "install -m 0755 -d /etc/apt/keyrings"
  run "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  run "chmod a+r /etc/apt/keyrings/docker.gpg"
  run "sh -c 'echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \$VERSION_CODENAME) stable\" > /etc/apt/sources.list.d/docker.list'"
  run "apt-get update -qq"
  run "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
fi

DOCKER_DAEMON="/etc/docker/daemon.json"
DOCKER_DAEMON_CONTENT='{
  "icc": false,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "live-restore": true,
  "no-new-privileges": true
}'
write_file "$DOCKER_DAEMON" "$DOCKER_DAEMON_CONTENT"
run "systemctl enable docker --quiet"
run "systemctl restart docker"
log_ok "Docker ready"

log_section "10/11 — Workspace"
run "mkdir -p ${APP_DIR} ${APP_DIR}/data"
run "chmod 750 ${APP_DIR}"
run "chmod 700 ${APP_DIR}/data"
if [[ "$DRY_RUN" == false && ! -f "${APP_DIR}/.env" ]]; then
  touch "${APP_DIR}/.env"
  chmod 600 "${APP_DIR}/.env"
fi
log_ok "Workspace ready at $APP_DIR"

log_section "11/11 — Unattended updates"
run "systemctl enable unattended-upgrades --quiet"
run "systemctl restart unattended-upgrades || true"
log_ok "Automatic security updates enabled"

echo -e "\n${GREEN}✔ Dedicated Opale Vault backend baseline complete.${NC}\n"
