name: "🔧 Opale Pay VPS Control (Start/Stop)"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action à exécuter sur la VM'
        required: true
        default: 'stop'
        type: choice
        options:
          - start
          - stop

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenStack Client on Runner
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3-openstackclient > /dev/null

      - name: Control VM Instance
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_NAME: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_IDENTITY_API_VERSION: "3"
        run: |
          echo "Sending ${{ github.event.inputs.action }} signal to opale-pay-prod..."
          openstack server ${{ github.event.inputs.action }} opale-pay-prod

          echo "Waiting for status verification..."
          sleep 5
          STATUS=$(openstack server show opale-pay-prod -c status -f value)
          echo "Current VM Status: $STATUS"
